language: go
go:
    - 1.5.4
    - 1.6.4
    - 1.7.4
    - release
    - tip

before_install:
    - go get github.com/jcloutz/fcc-go-timestamp-microservice
    - go get github.com/tools/godep
install:
    - godep restore
script:
    - go test -v -cover ./...
